### PR TITLE
feat: delete Helm PR releases older than a week

### PR DESCRIPTION
**Pull request by DerekRoberts**
---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://quickstart-openshift-1496-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1496-frontend.apps.silver.devops.gov.bc.ca/api)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/analysis.yml)

After merge, new images are promoted to:
- [Merge Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/merge-main.yml)

### CODE REVIEW

**Comment by DerekRoberts** [comment]
https://kubernetes.io/docs/reference/kubectl/jsonpath/

https://stackoverflow.com/questions/63249772/how-to-delete-helm-release-older-than-1-month

**Comment by DerekRoberts** [comment]
Helm has a TTL (time to live)!  Investigate.  Closing this PR.
https://github.com/JovianX/helm-release-plugin

**Comment by mishraomp** [comment]
@DerekRoberts are we on HELM 2(https://v2.helm.sh/docs/helm/#helm-delete), since `delete` is now uninstall in HELM3 https://helm.sh/docs/helm/helm_delete/

**Comment by DerekRoberts** [comment]
Thanks! Fixing. :)

**Pull request merged**
