### PR TITLE
feat: using ingress with derived hostname <releasename>.<domain>/<com…

### PR DESCRIPTION
**Pull request by cberg-aot**
…ponentname>

# Description

Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://quickstart-openshift-1995-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1995-frontend.apps.silver.devops.gov.bc.ca/api)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/merge.yml)

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://quickstart-openshift-1995.apps.silver.devops.gov.bc.ca/frontend)
  #- [Backend](https://quickstart-openshift-1995.apps.silver.devops.gov.bc.ca/api)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/merge.yml)

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://quickstart-openshift.apps.silver.devops.gov.bc.ca/frontend)
- [Backend](https://quickstart-openshift.apps.silver.devops.gov.bc.ca/api)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/merge.yml)

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://quickstart-openshift-1995.apps.silver.devops.gov.bc.ca/frontend)
- [Backend](https://quickstart-openshift-1995.apps.silver.devops.gov.bc.ca/api)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/merge.yml)

### CODE REVIEW

**Comment by cberg-aot** [comment]
@DerekRoberts  can you help debug why this is not loading frontend?  I experimented with onroute and had a similar refactor working

**Comment by DerekRoberts** [comment]
@cberg-aot Very nice! I'm off until Monday, but think this is close. Thanks for the improvement! :)

**Comment by mishraomp** [comment]
why do we need this refactor? I don't see any value TBH @cberg-aot @DerekRoberts

**Comment by DerekRoberts** [comment]
@mishraomp We'd like to go pure k8s, favoring ingress over routes.

**Comment by mishraomp** [comment]
> @mishraomp We'd like to go pure k8s, favoring ingress over routes.

which we already do

**Pull request closed without merging**
