### PR TITLE
feat(ci): node 22

### LINKED ISSUE #1966: Support Node.js version 22
Node.js 22 is released as current, lets start exploring to migrate workloads to 22 and see what impacts we are seeing.

### PR DESCRIPTION
**Pull request by DerekRoberts**
Closes #1966

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://quickstart-openshift-1982-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1982-backend.apps.silver.devops.gov.bc.ca/api)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/merge.yml)

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://quickstart-openshift-1982-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1982-frontend.apps.silver.devops.gov.bc.ca/api)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/merge.yml)

### CODE REVIEW

**Comment by mishraomp** [comment]
now after deployment we are getting
```
PrismaClientInitializationError: Prisma Client could not locate the Query Engine for runtime "debian-openssl-3.0.x".

This happened because Prisma Client was generated for "debian-openssl-1.1.x", but the actual deployment required "debian-openssl-3.0.x".
Add "debian-openssl-3.0.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it:

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-3.0.x"]
}

The following locations have been searched:
  /app/node_modules/.prisma/client
  /app/node_modules/@prisma/client
  /tmp/prisma-engines
    at wa (/app/node_modules/@prisma/client/runtime/library.js:64:805)
    at async Object.loadLibrary (/app/node_modules/@prisma/client/runtime/library.js:111:10060)
    at async wt.loadEngine (/app/node_modules/@prisma/client/runtime/library.js:112:448)
    at async wt.instantiateLibrary (/app/node_modules/@prisma/client/runtime/library.js:111:12829) {
  clientVersion: '5.15.0',
  errorCode: undefined
}

Node.js v22.3.0
```
will look into it @DerekRoberts

**Comment by DerekRoberts** [comment]
@mishraomp All good. Thanks for staying on top of this. :)

**Comment by mishraomp** [comment]
all set @DerekRoberts :)

**Review by mishraomp — APPROVED** [review]
Node 22, 😍

**Pull request merged**
