### PR TITLE
Update merge-main.yml

### PR DESCRIPTION
**Pull request by mishraomp**
---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://quickstart-openshift-1395-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1395-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-1395-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-1395-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-1395-backend-go.apps.silver.devops.gov.bc.ca)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/analysis.yml)
- [Tests Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/tests.yml)

After merge, new images are promoted to:
- [Main Merge Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/merge-main.yml)

### CODE REVIEW

**Comment by mishraomp** [comment]
https://github.com/bcgov/quickstart-openshift/issues/1392

**Review by DerekRoberts — APPROVED** [review]
Much better than my terrible PR.  :)

**Comment by mishraomp** [comment]
> Much better than my terrible PR. :)

I  am not 100% sure, just trying LTS vs snapshot, hope it works 🤞🏼

**Comment by DerekRoberts** [comment]
> > Much better than my terrible PR. :)
> 
> I am not 100% sure, just trying LTS vs snapshot, hope it works 🤞🏼

Well, you were 100% right.  Good job!  :D

https://github.com/bcgov/quickstart-openshift/actions/runs/6208498430/job/16854738499

**Pull request merged**
